version: '3'
services:
    web:
        image: python:latest
        ports:
            - 80:5000
        tty: true
        volumes:
            - ./src/:/src
            - ./requirements.txt/:/requirements.txt
        working_dir: /src
        command: bash -c 'pip install -r /requirements.txt && python app.py'
        depends_on:
            - redis
    redis:
        image: redis:alpine